config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 #顧客
  scope module: :public do

   root "homes#top"
   get "/about" => "homes#about", as: "about"


    # 会員
      get "customers/out" => "customers#out" #顧客の退会確認画面
      patch "customers/withdraw" => "customers#withdraw" #顧客の退会処理(ステータスの更新)
      get "customers/my_page" => "customers#show"
      get "customers/information/edit" => "customers#edit"
      patch "customers/information" => "customers#update"

    #商品
     resources :items, only: [:index, :show]

     delete "cart_items/destroy_all" => "cart_items#destroy_all"
     resources :cart_items, only: [:new, :create, :index, :show, :destroy,:update]



   #注文
   get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    post "orders/confirm" => "orders#confirm"

   #配送先
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]



  end


   #管理者
   namespace :admin do
     resources :items, only: [:index, :new, :create, :show, :update, :edit]
     resources :genres, only: [:index, :new, :create, :update, :edit]
     resources :customers, only: [:index, :show, :update, :edit]

     resources :orders, only: [:index, :update, :show]

     root  "homes#top"
   end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  validates :post_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.post_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  validates :item_id, uniqueness: { scope: :customer_id }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  def subtotal
    item.with_tax_price * quantity  #税込価格＊数量
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :addresses, dependent: :destroy#配送先
         has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  #バリデーション
  validates :name, presence: true
 # validates :name, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :itm_image_url

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  #バリデーション
  validates :name, presence: true
  validates :text, presence: true
  validates :price, presence: true

  
  def with_tax_price
   (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1,  production: 2, preparing: 3,  shipped: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item


  enum making_status: { impossible: 0, waiting: 1, production: 2, completion: 3 }

  def subtotal
    purchase_price * quantity
  end

end

app/controllers/admin/genre_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path(@genre), notice: "You have created book successfully."
    else
      @genre = Genre.all
      render 'index'
    end
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def edit
     @genre = Genre.find(params[:id])
  end

   private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "投稿が成功しました"
      redirect_to admin_genres_path
    else
      @genre = Genre.all
      render 'index'
    end
  end

   def edit
     @genre = Genre.find(params[:id])
   end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "編集が成功しました"
      redirect_to admin_genres_path
    else
      @genre = Genre.find(params[:id])
      render "edit"
    end
  end



   private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
  def top
    @orders = Order.where("created_at" === Date.today)

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "投稿が成功しました"
      redirect_to admin_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
      render :new
    end
  end

    def show
      @item = Item.find(params[:id])
    end

    def edit
      @item = Item.find(params[:id])

    end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "更新できました"
      redirect_to admin_item_path(@item)
    else
      render :edit
      @item.Item.find(params[:id])
    end
  end


  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :text, :is_sales_status, :price, :itm_image_url)#ジャンルid・名前・文・状態・税込価格・写真
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!


  def index


    @orders = Order.all


  end


	def show
		@order = Order.find(params[:id])
		@order_details = @order.order_details
		
	end


	def total(items_total_price)

	end

	def update
		order = Order.find(params[:id])
		order_details = order.order_details
    order.update(order_params)

		if order.order_status == "入金確認"
			order_details.update_all(making_status: "製作待ち")
		end
		redirect_to admin_order_path(order.id)
	end

  private
	def order_params
		params.require(:order).permit(:order_status)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admin_root_path
        when Customer
          root_path
  		end
	  end


    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :tel])
    end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<h2 class="admin-homes-top-title">管理者画面</h2>

<div class="row admin-homes-top-message">
  <span class="col-xs-3">本日の注文件数</span>
  <span class="col-xs-9">

    <%= @orders.count %>件

  </span>
  

</div>

app/views/admin/items/_input.html.erb
<div class="container mt-5 mb-5">
 <div class="row my-3">



<!--新規投稿・editページの共有-->
<%= form_with model: [:admin,item] do |f| %>
<table class="table">
<thead>
  </thead>
  <tbody>
  <tr>
    <th scope="row">画像</th>
   <td><%= f.file_field :itm_image_url,accept:'itm_image_url/*' %></td>
  </tr>
  <tr>
    <th scope="row">商品名</th>
    <td><%= f.text_field :name %></td>
  </tr>
  <tr>
    <th scope="row">商品説明</th>
    <td><%= f.text_area :text %></td>
  </tr>
   <tr>
    <th scope="row">税込価格</th>
    <td><%= f.text_field :price %></td>
  </tr>
  <tr>
    <th scope="row">販売状況</th>
    <td><%= f.select :is_sales_status, [["販売中","false"], ["販売不可","true"]], include_blank: "--選択してください--" %></td>
  </tr>
  <tr>
    <th scope="row">販売ジャンル</th>
    <td> <%= f.collection_select :genre_id, Genre.all ,:id, :name, include_blank: "--選択してください--" %></td>
  </tr>

 </tbody>
</table>
 <div>
     <%= f.submit class: "col-xs-2 pull-right btn-lg btn-success "  %>
 </div>
  <% end %>
 </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container mt-5 mb-5">
<div class="row my-3">
<h1>商品編集</h1>
<!--エラー文->
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!--共有テンプレート-->
<%= render 'input', item: @item %>

<!--一つ前のページに戻る-->
<%= link_to :back do %>
  <button>戻る</button>
<% end %>
</div>
</div>

app/views/admin/items/index.html.erb
<h1>商品一覧</h1>
<!--投稿成功時のメッセージ-->
<%= flash[:notice] %>

<div class="row">
<div class="col-xs-12">
 <table class="table table-hover ">
  <thead>
    <th center>
<!--newページへのリンク-->
<%= link_to "商品の追加", new_admin_item_path %>
</th>
</thead>

<!--一覧表示-->


<tbody>
  <tr>
    <th>商品ID</th>
    <td>商品名</td>
    <td>税込価格</td>
    <td>ジャンル</td>
    <td>販売状況</td>
  </tr>
  <% @items.each do |item| %>
  <tr>
    <!--showページへのリンク-->
    <th><%= item.id %></th>
    <td>
      <%=link_to admin_item_path(item.id) do %>
      <%= item.name %>
      <% end %>
    </td>
    <td><%= item.price %></td>
    <td><%= item.genre.name %></td>
    <td>
      <% if item.is_sales_status == false %>
        販売中
      <% else %>
        販売停止中
      <% end %>
    </td>
  </tr>
  <% end %>
</tbody>
</table>

app/views/admin/items/new.html.erb
<div class="container mt-5 mb-5">
<div class="row my-3">
<h1>商品新規登録</h1>
</div>
<!--投稿失敗時のメッセージ-->
<% if @item.errors.any? %>
  <%= @item.errors.count %>件のエラーが発生しました
  <ul>
    <% @item.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<!--共有テンプレート-->
<%= render 'input', item: @item %>
<!--前のページに戻る-->
<div>
<%= link_to admin_items_path do %>
 <button>戻る</button>

<% end %>
</div>
</div>

app/views/admin/items/show.html.erb
<div class="container mt-5 mb-5">
<div class="row my-3">
<h1>商品詳細</h1>
<%= flash[:notice] %>
<!--編集画面表示-->

<div class="row">
<div class="col-xs-12">
 <table class="table table-hover ">
  <thead></thead>
  <tbody>
  <tr>
     <th>商品名</th>
      <td><%= @item.name %></td>
  </tr>
  <tr>
     <th>商品画像</th>
      <td><%= image_tag @item.itm_image_url %></td>
  </tr>
  <tr>
    <th>商品説明</th>
    <td><%= @item.text %></td>
   </tr>
   <tr>
     <th>ジャンル</th>
     <td><%= @item.genre.name %></td>
    </tr>
    <tr>
      <th>税込価格</th>
      <td><%= @item.price %></td>
    </tr>
    <tr>
      <th>販売状況</th>
      <td>
      <% if @item.is_sales_status == false %>
        販売中
      <% else %>
        販売停止中
      <% end %>
      </td>
    </tr>
    <tr>
      <th>
       <%= link_to edit_admin_item_path(@item.id) ,class: "col-xs-2 pull-right btn-lg btn-success " do %>
           編集
       <% end %>
      </th>
    </tr>
</tbody>
</table>
</div>
</div>
<!--一つ前のページに戻る-->
<div>
<%= link_to admin_items_path do %>
  <button>商品一覧画面</button>
<% end %>
</div>
</div>
</div>

app/views/admin/orders/index.html.erb
<%#<div class="pull-right">
	<%= search_form_for(@search, url:admins_orders_path) do |f| %>
		<%#<%= f.label :name, "注文履歴キーワード" %>
		<%#<%= f.search_field :name_cont %>
		<%#<%= f.submit %>
	<%#<% end %>
<%#</div>%>


  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h2>注文一覧</h2>


    <div class="order-table">
      <table class="table">
        <thead>
          <tr>
            <th>購入日時</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>

        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= link_to order.created_at.strftime("%Y-%m-%d %H:%M:%S"), admin_order_path(order) %></td>
              <td><%= order.customer.last_name + "　" + order.customer.first_name %></td>
              <td><%= order.order_details.sum(:quantity) %></td>
              <td><%= order.order_status %></td>
            </tr>
            <% end %>

            <%#<%= paginate @orders %>

        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <div class="row">
      <h2>注文明細</h2>


  <div class="col-xs-7">
    <table class="table">
      <tbody>
      <tr>
        <th>購入者</th>
        <td><%= link_to admin_customer_path(@order.customer) do %>
        <%= @order.customer.first_name %>
        <%= @order.customer.last_name %>
        <% end %>
        </td>
      </tr>

      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>

      <tr>
        <th>支払方法</th>
        <td><%= @order.payment_method %></td>
      </tr>

      <tr>
        <th>注文ステータス</th>
        <td>
        <%= form_for (@order), url:admin_order_path(@order) do |f| %>
        <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
        <%= f.submit "更新", class: "btn btn-success" %>
        <% end %>
        </td>
      </tr>

    </tbody>
  </table>

      <table class="table">
        <thead>
          <tr>
            <th>商品名</th>
            <th>単価（税込）</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>


        <tbody>
      <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <%#<td><%= (order_detail.purchase_price).floor.to_s(:delimited, delimiter: ',') %>
             <td><%= order_detail.item.price %></td>
            <td><%= order_detail.quantity %></td>
            <td><%= order_detail.item.price*  order_detail.quantity %></td>
            <%#<td><%= (order_detail.purchase_price * order_detail.quantity).floor.to_s(:delimited, delimiter: ',') %>
            <td>
              <%= form_for (order_detail), url:admin_order_path(order_detail) do |f|  %>
              <%= f.select :making_status, OrderDetail.making_statuses.keys.map {|k| [I18n.t("enums.order_detail.making_status.#{k}"), k]} %>
              <%= f.submit '更新',class:"btn btn-success" %>
              <% end %>
            </td>
          </tr>

          <% end %>
        </tbody>
      </table>
    </div>

    <br><br><br><br><br><br><br><br><br><br>
    <div class="col-xs-4">
      <table class="table">
        <tbody>

          <tr>
            <td>商品合計</td>
            <td><%= @order.order_details.sum(&:subtotal).to_s(:delimited, delimiter: ',') %></td>
          </tr>

          <tr>
            <td>送料</td>
            <td><%= @order.postage.to_s(:delimited, delimiter: ',') %></td>
          </tr>

          <tr>
            <td>請求合計金額</td>
           <td><%= @order.total_cost.to_s() %></td>
          </tr>
        </tbody>
      </table>
     </div>
    </div>
  </div>

app/views/items/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 px-sm-0">
      <h1>商品一覧</h1><h4>(全<%= @total_items.count %>件)</h4>
    </div>
  </div>
  <div class="row mt-3 mb-3 text-center text-xs-center text-sm-center text-md-left">
      <% @items.each do |item| %>
      <div class="col-xs-10 col-sm-10 col-md-6 col-lg-3">
       <div class="card w-100 bg-transparent border-0" style="width: 18rem;">
        <%= link_to item_path(item.id) do %>
          <p class="img-wrap"><%= attachment_image_tag item, :image, size: "180x130", fallback: "no_image.jpg" %></p>
        <% end %>
        <div class="card-body">
          <p class="item-details item-name card-text"><%= item.name %></p>
          <% if item.is_active == true %>
            <p class="item-details card-text">¥<%= (item.price * 1.08).to_i.to_s(:delimited, delimiter: ',') %></p>
          <% else %>
            <p class="text-danger font-weight-bold card-text">売り切れ</p>
        <% end %>
        </div>
      </div>
    </div>
      <% end %>
  </div> 
      <%= paginate(@items) %>
</div>

app/views/items/show.html.erb
<%= attachment_image_tag @item, :image, size: "340x220", fallback: "no_image.jpg" %>
<h2><%= @item.name %></h2>
<p><%= @item.introduction %></p>
<% if @item.is_active == true %>
  <h3>¥<%= (@item.price * 1.08).to_i.to_s(:delimited, delimiter: ',') %></h3>
  <p>(税込)</p>
  <%= form_with model:@cart_item, url: cart_items_path, method: :post do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.select :count, (1..10).to_a, include_blank: "個数選択" %>
    <%= f.submit "カートに入れる", class: "btn btn-success" %>
  <% end %>
<% else %>
  <h3>売り切れ</h3>
<% end %>