config/routes.rb
Rails.application.routes.draw do

# 顧客用
# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

 #顧客
  scope module: :public do

   root "homes#top"
   get "/about" => "homes#about", as: "about"


    # 会員
      get "customers/out" => "customers#out" #顧客の退会確認画面
      patch "customers/withdraw" => "customers#withdraw" #顧客の退会処理(ステータスの更新)
      get "customers/my_page" => "customers#show"
      get "customers/information/edit" => "customers#edit"
      patch "customers/information" => "customers#update"

    #商品
     resources :items, only: [:index, :show]

     delete "cart_items/destroy_all" => "cart_items#destroy_all"
     resources :cart_items, only: [:new, :create, :index, :show, :destroy,:update]



   #注文
   get "orders/complete" => "orders#complete"
    resources :orders, only: [:new, :create, :index, :show]
    post "orders/confirm" => "orders#confirm"

   #配送先
    resources :addresses, only: [:create, :index, :edit, :update, :destroy]



  end


   #管理者
   namespace :admin do
     resources :items, only: [:index, :new, :create, :show, :update, :edit]
     resources :genres, only: [:index, :new, :create, :update, :edit]
     resources :customers, only: [:index, :show, :update, :edit]

     resources :orders, only: [:index, :update, :show]

     root  "homes#top"
   end




  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.htm
end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer
  validates :post_code, length: {is: 7}, numericality: { only_integer: true }, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def shipping_address_for_view
  	self.post_code + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item
  validates :item_id, uniqueness: { scope: :customer_id }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

  def subtotal
    item.with_tax_price * quantity  #税込価格＊数量
  end
  
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :cart_items, dependent: :destroy
         has_many :addresses, dependent: :destroy#配送先
         has_many :orders, dependent: :destroy
end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

  #バリデーション
  validates :name, presence: true
 # validates :name, uniqueness: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :itm_image_url

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  #バリデーション
  validates :name, presence: true
  validates :text, presence: true
  validates :price, presence: true

  
  def with_tax_price
   (price * 1.1).floor
  end


end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_details, dependent: :destroy
  belongs_to :customer

  has_many :order_details

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { waiting: 0, confirmation: 1,  production: 2, preparing: 3,  shipped: 4 }


end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item


  enum making_status: { impossible: 0, waiting: 1, production: 2, completion: 3 }

  def subtotal
    purchase_price * quantity
  end

end

app/controllers/admin/genre_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def new
    @genre = new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path(@genre), notice: "You have created book successfully."
    else
      @genre = Genre.all
      render 'index'
    end
  end

  def update
     @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path(@genre), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def edit
     @genre = Genre.find(params[:id])
  end

   private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!
  def top
    @orders = Order.where("created_at" === Date.today)

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      flash[:notice] = "投稿が成功しました"
      redirect_to admin_item_path(@item)
    else
      flash[:genre_created_error] = "ジャンル名を入力してください"
      render :new
    end
  end

    def show
      @item = Item.find(params[:id])
    end

    def edit
      @item = Item.find(params[:id])

    end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:notice] = "更新できました"
      redirect_to admin_item_path(@item)
    else
      render :edit
      @item.Item.find(params[:id])
    end
  end


  private
  def item_params
    params.require(:item).permit(:genre_id, :name, :text, :is_sales_status, :price, :itm_image_url)#ジャンルid・名前・文・状態・税込価格・写真
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  
  before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_in_path_for(resource)
      case resource
        when Admin
          admin_root_path
        when Customer
          root_path
  		end
	  end


    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :encrypted_password, :last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :tel])
    end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header_admin.html.erb
<div class= "admin-header">
  <div class= "admin-nav-bars">
      <nav class="nav navbar-brand navbar-left header-logo">
      <%#<%= link_to admins_root_path,class:"header-logo-letter" do %><%#<%= image_tag('logo.png', class: 'admin_shop_logo') %><%#<% end %>
    </nav>
    <nav class="nav navbar-nav">
      <span class="adjust">
      </span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to admin_items_path,class:"admin-nav-item" do %><i class="glyphicon glyphicon-user users"></i>&emsp;商品一覧<% end %>
        </li>
        <li class="">
          <%= link_to  admin_customers_path,class:"admin-nav-item" do %><i class="glyphicon glyphicon-home home"></i>&emsp;会員一覧<% end %>
        </li>
        <li>
          <%= link_to admin_orders_path,class:"admin-nav-item" do %><i class="glyphicon glyphicon-book books"></i>&emsp;注文履歴一覧<% end %>
        </li>
        <li class="">
          <%= link_to  admin_genres_path,class:"admin-nav-item" do %><i class="glyphicon glyphicon-home home"></i>&emsp;ジャンル一覧<% end %>
        </li>
        <li>
          <%= link_to destroy_admin_session_path,class:"admin-nav-item", method: :delete do %><i class="glyphicon glyphicon-log-out logout"></i>&emsp;ログアウト<% end %>
        </li>
      </ul>
    </nav>

app/views/layouts/_header_customer.html.erb
<nav class="nav navbar-nav">
  <span class="client-name  login-client-name">
    ようこそ、<%= current_customer.first_name %><%= current_customer.last_name %>さん！
  </span>
  </nav>
  <nav>
    <ul class="nav navbar-nav navbar-right">
      <li class="">
        <%= link_to customers_my_page_path,class:"nav-item" do %><i class="fas fa-user"></i>マイページ<% end %>
      </li>
      <li>
        <%= link_to items_path,class:"nav-item" do %><i class="fas fa-gift"></i>商品一覧<% end %>
      </li>
      <li>
        <%= link_to cart_items_path,class:"nav-item" do %><i class="fas fa-cart-plus"></i>カート<% end %>
      </li>
      <li>
        <%= link_to destroy_customer_session_path,class:"nav-item", method: :delete do %><i class="fas fa-arrow-right"></i>ログアウト<% end %>
      </li>
    </ul>
  </nav>

app/views/layouts/_header_logout.html.erb
<nav>
  <ul class="nav navbar-nav navbar-right">
    <li>
      <%= link_to about_path,class:"nav-item" do %><i class="fas fa-store-alt"></i>About<% end %>
    </li>

    <li>

    <%= link_to items_path ,class:"nav-item" do %><i class="fas fa-gift"></i>商品一覧<% end %>

    </li>
    <li>
      <%= link_to new_customer_registration_path ,class:"nav-item" do %><i class="fas fa-user-plus"></i>新規登録<% end %>
    </li>
    <li>
      <%= link_to new_customer_session_path ,class:"nav-item" do %><i class="fas fa-check"></i>ログイン<% end %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="https://kit.fontawesome.com/5667bc939f.js" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  </head>

 <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-right">
        <div class="container">
          <%#<a class="navbar-brand" href="/"><%= image_tag "logo3.png", :size => "240x50" %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
          　<h1>NaganoCake</h1>
            <ul class="navbar-nav ms-auto">
              <!--adminログイン時のヘッダー-->
            <% if admin_signed_in? %>
             <%= render 'layouts/header_admin' %>

            <!--customersログイン時のヘッダー-->
            <% elsif customer_signed_in? %>
             <%= render 'layouts/header_customer' %>
            <% else %>
            <!--ログイン前時のヘッダー-->
             <%= render 'layouts/header_logout' %>
           <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class="container">
  			<div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
        <% flash.each do |key, value| %>
          <p class="alert alert-<%= key %>">
            <%= sanitize value, tags: %w(br) %>
          </p>
        <% end %>
      </div>
    </div>
    <main>
      <%= yield %>
    </main>
    
    <footer>
      <%#<%= render "layouts/footer" %>
    </footer>
  </body>
</html>